# Generated by Django 3.1.5 on 2021-03-01 23:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(default=api.models.generate_room_code, max_length=6, unique=True)),
                ('host_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
