# Generated by Django 3.1.5 on 2021-03-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_games_cards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='cards',
            field=models.CharField(default=[''], max_length=255),
        ),
    ]
