# Generated by Django 3.1.5 on 2021-03-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210303_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_code',
            field=models.CharField(default='F80AB', max_length=6, unique=True),
        ),
    ]
