# Generated by Django 3.1.5 on 2021-03-03 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210303_2018'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
