# Generated by Django 3.1.5 on 2021-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0005_delete_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_code', models.CharField(default='0FB5D', max_length=6, unique=True)),
                ('host_id', models.CharField(max_length=50, unique=True)),
                ('cards', models.CharField(default=[''], max_length=255)),
            ],
        ),
    ]
