# Generated by Django 3.1.5 on 2021-03-03 20:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210303_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='game_code',
            field=models.CharField(default=api.models.generate_game_code, max_length=6, unique=True),
        ),
    ]
